version: '3.7'

services:
  p2c-redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: p2c-redis
    hostname: p2c-redis

  p2c-io:
    build: ./io
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=p2c-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=__________
      - CONTROLLER_PORT=8080
    container_name: p2c-io
    hostname: p2c-io
    ports:
    - 8080:8080

  p2c-controller:
    build: ./controller
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=p2c-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=__________

  p2c-service:
    build: ./services
    restart: unless-stopped
    environment:
      - REDIS_HOSTNAME=p2c-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=__________
